CREATE TABLE "message_templates" (
	"key" text PRIMARY KEY NOT NULL,
	"channel" text DEFAULT 'email' NOT NULL,
	"fr" jsonb NOT NULL,
	"en" jsonb NOT NULL,
	"updated_at" text NOT NULL,
	"updated_by" text
);
--> statement-breakpoint
-- Seed the 3 templates that already replace hardcoded emails (contact_ack,
-- apply_ack, starlink_reminder) with their exact current copy, plus the new
-- starlink_help_notify_technician default, so day-one behavior is
-- unchanged. Content mirrors lib/email/template-registry.ts's defaults.
INSERT INTO "message_templates" ("key", "channel", "fr", "en", "updated_at", "updated_by") VALUES ('contact_ack', 'email', '{"subject":"Nous avons bien reçu votre message","body":"<h2>Merci de nous avoir contactés, {{firstName}}</h2>\n        <p>Nous avons bien reçu votre message concernant : <strong>{{subject}}</strong>.</p>\n        <p>Notre équipe vous répondra dans les plus brefs délais.</p>\n        <p>— L''équipe Cyber PolCo</p>"}'::jsonb, '{"subject":"We''ve received your message","body":"<h2>Thank you for contacting us, {{firstName}}</h2>\n        <p>We''ve received your message regarding: <strong>{{subject}}</strong>.</p>\n        <p>Our team will get back to you shortly.</p>\n        <p>— The Cyber PolCo team</p>"}'::jsonb, '2026-08-04T00:00:00.000Z', NULL) ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint
INSERT INTO "message_templates" ("key", "channel", "fr", "en", "updated_at", "updated_by") VALUES ('apply_ack', 'email', '{"subject":"Votre candidature a bien été reçue","body":"<h2>Merci pour votre candidature, {{name}}</h2>\n        <p>Nous avons bien reçu votre candidature pour le poste de <strong>{{jobTitle}}</strong>.</p>\n        <p>Notre équipe RH examinera votre dossier et vous recontactera si votre profil correspond.</p>\n        <p>— L''équipe Cyber PolCo</p>"}'::jsonb, '{"subject":"Your application has been received","body":"<h2>Thank you for applying, {{name}}</h2>\n        <p>We''ve received your application for the <strong>{{jobTitle}}</strong> position.</p>\n        <p>Our HR team will review your profile and reach out if it''s a match.</p>\n        <p>— The Cyber PolCo team</p>"}'::jsonb, '2026-08-04T00:00:00.000Z', NULL) ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint
INSERT INTO "message_templates" ("key", "channel", "fr", "en", "updated_at", "updated_by") VALUES ('starlink_reminder', 'email', '{"subject":"Rappel : votre abonnement Starlink expire bientôt / Reminder: your Starlink subscription expires soon","body":"<h2>Bonjour {{clientName}},</h2>\n      <p>Votre abonnement Starlink pour le site <strong>{{siteName}}</strong> expirera le <strong>{{expiryDate}}</strong>, dans 7 jours.</p>\n      <p>Pour éviter toute interruption de service, veuillez contacter notre équipe pour renouveler votre abonnement :</p>\n      <ul>\n        <li>Email : <a href=\"mailto:info@cyberpolco.com\">info@cyberpolco.com</a></li>\n        <li>WhatsApp RDC : <a href=\"https://wa.me/243828117710\">https://wa.me/243828117710</a></li>\n        <li>WhatsApp Namibie : <a href=\"https://wa.me/264812314352\">https://wa.me/264812314352</a></li>\n      </ul>\n      <p>— L''équipe Cyber PolCo</p>"}'::jsonb, '{"subject":"Rappel : votre abonnement Starlink expire bientôt / Reminder: your Starlink subscription expires soon","body":"<h2>Hello {{clientName}},</h2>\n      <p>Your Starlink subscription for site <strong>{{siteName}}</strong> will expire on <strong>{{expiryDate}}</strong>, in 7 days.</p>\n      <p>To avoid any service interruption, please contact our team to renew your subscription:</p>\n      <ul>\n        <li>Email: <a href=\"mailto:info@cyberpolco.com\">info@cyberpolco.com</a></li>\n        <li>WhatsApp DRC: <a href=\"https://wa.me/243828117710\">https://wa.me/243828117710</a></li>\n        <li>WhatsApp Namibia: <a href=\"https://wa.me/264812314352\">https://wa.me/264812314352</a></li>\n      </ul>\n      <p>— The Cyber PolCo team</p>"}'::jsonb, '2026-08-04T00:00:00.000Z', NULL) ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint
INSERT INTO "message_templates" ("key", "channel", "fr", "en", "updated_at", "updated_by") VALUES ('starlink_help_notify_technician', 'email', '{"subject":"Nouvelle demande d''assistance Starlink","body":"<p>{{clientName}} ({{clientId}}) a besoin d''assistance sur le site <strong>{{siteName}}</strong>.</p>"}'::jsonb, '{"subject":"New Starlink assistance request","body":"<p>{{clientName}} ({{clientId}}) needs assistance at site <strong>{{siteName}}</strong>.</p>"}'::jsonb, '2026-08-04T00:00:00.000Z', NULL) ON CONFLICT ("key") DO NOTHING;
